name: Test Workflow

on:
  workflow_call:
    inputs:
      ENVIRONMENTSS:
        required: true
        type: string
      VARIABLESS:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORK_DIR: .
      ENVIRONMENTSS: ${{ inputs.ENVIRONMENTSS }}
      VARIABLESS: ${{ inputs.VARIABLESS }}

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          VAR=$(echo "$ENVIRONMENTSS" | base64)
          VER=$(echo "$VARIABLESS" | base64)
          echo $VAR > /tmp/test_remote.log
          echo $VER >> /tmp/test_remote.log

      - name: Upload Tests report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-remote-report
          path: /tmp/test_remote.log
